[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW-FROM https://www.arkeyltd.com"
    Content-Security-Policy = "frame-ancestors 'self' https://www.arkeyltd.com https://*.arkeyltd.com"
